[package]
name = "invoice-pdf-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
fantoccini = "0.22.0"
minijinja = { version = "2.15.1", features = ["loader"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
